### ISSUE TITLE
Importing reflect metadata

### ISSUE THREAD

**Issue by irissoftworks** [odavid/typeorm-transactional-cls-hooked#11]
Thanks for the amazing work with this package.

One quick question, I realized at the index:
`import 'reflect-metadata'` 

This may cause issues if it is included twice, and the official typeorm doc recommends importing it.

I was wondering if importing reflect-metadata should be kept as consumer responsibility, or alternatively could the doc be updated to point out the fact that it is included already ?

**Comment by odavid** [comment]
@irissoftworks - Sorry for that. 
Removed it.
