### ISSUE TITLE
library architecture

### ISSUE THREAD

**Issue by NarHakobyan** [odavid/typeorm-transactional-cls-hooked#19]
please remove types from dist folder, if we are not importing from dist types are not working

![image](https://user-images.githubusercontent.com/1781506/55382116-e54a7300-5535-11e9-8c99-7c87070cb6b0.png)

![image](https://user-images.githubusercontent.com/1781506/55382180-0e6b0380-5536-11e9-80e4-15c78cdb0dab.png)

**Comment by odavid** [comment]
Why are you importing from dist?

**Comment by NarHakobyan** [comment]
In that case typings autocomplete is not working

**Comment by odavid** [comment]
It should work, will investigate.

**Comment by odavid** [comment]
@NarHakobyan - I just created a simple typescript project
* installed typeorm, typeorm-transactional-cls-hooked, reflect-metadata

intellisense works
![image](https://user-images.githubusercontent.com/861953/55387904-f6e24980-553a-11e9-8ab1-3ab59017cdfa.png)

**Comment by NarHakobyan** [comment]
![image](https://user-images.githubusercontent.com/1781506/55401396-afbb7f00-5561-11e9-9cdb-51f3b58f08f5.png)
![image](https://user-images.githubusercontent.com/1781506/55401404-b944e700-5561-11e9-9116-5044ba6837e1.png)

also, webstorm autoimport imports from dist

**Comment by odavid** [comment]
Hi @NarHakobyan - Added types to package.json, I believe it will solve the issue.

Will release soon.

Closing it, please reopen if the new release won't work.

Cheers,
Ohad
