### ISSUE TITLE
Not working with Nestjs 6

### ISSUE THREAD

**Issue by ondrakub** [odavid/typeorm-transactional-cls-hooked#23]
With Nestjs version 6 it is not working.

When I can use repository in service:
```
constructor(
    private readonly userRepository: UserRepository
  ) {}
```
I got error that It cannot resolve dependencies...

**Comment by odavid** [comment]
@ondrakub - Not sure I understand.
Can you please give more details such as:
* package.json - to see which package versions your are using.
* Scenario and detailed error message
* Database type

Did it work for you before on this project?
I am not sure where did you use the `@Transactional` and how. Can you elaborate?

**Comment by ondrakub** [comment]
yes, with nest js 5 (`"@nestjs/common": "5.7.4"` etc..) it works.

I can prepare small repository with example or if I just describe it here?

**Comment by odavid** [comment]
Small repository will be super great!

**Comment by ondrakub** [comment]
I'm so sorry.
We did not have the latest minor version of nestjs 6. It works now.
Thank you for your time. I'm closing the issue.
