### ISSUE TITLE
Does it support ActiveRecord mode?

### ISSUE THREAD

**Issue by metauro** [odavid/typeorm-transactional-cls-hooked#26]
seems the document only say how to use it for DataMapper mode

**Comment by odavid** [comment]
Hi,
Although I have never tested this mode, I believe it will work if you will patch the repository instances. See [Patching typeorm repository with base repository](https://github.com/odavid/typeorm-transactional-cls-hooked#patching-typeorm-repository-with-baserepository)

**Comment by metauro** [comment]
👍 it works, thanks a lot.
