### ISSUE TITLE
Custom Repositories without BaseRepository or Repository

### ISSUE THREAD

**Issue by th3neken** [odavid/typeorm-transactional-cls-hooked#29]
Hi there!

In my project, I don't extend by BaseRepository or Repository. In my repository class, I use @InjectRepisitoryManager() to use EntityManager. Eg. 

`@Injectable()
export class TestRepository {
    constructor(@InjectEntityManager() private readonly entityManager: EntityManager) {}
`

In this case, a Transactional() seems to not working properly. I saw in logs START TRANSACTION and ROLLBACK on an error but still, others (correct ones)  operations are executed on the database. Is there a way to fix this?

**Comment by odavid** [comment]
Hi @th3neken,

I have not tried that, but I believe that if you will look at [This code](https://github.com/odavid/typeorm-transactional-cls-hooked/blob/master/src/patch-typeorm-repository.ts), it might help.

Basically, I believe you can do it as follows:

```typescript
Object.getOwnPropertyNames(BaseRepository.prototype).forEach(pName =>
    Object.defineProperty(TestRepository.prototype, pName, Object.getOwnPropertyDescriptor(
      BaseRepository.prototype,
      pName
    ) as PropertyDescriptor)
  )
```

Cheers,
Ohad

**Comment by th3neken** [comment]
It doesn't work. But when just extend by BaseRepository everything starts working. Thank you for your help!
