### ISSUE TITLE
typeorm-transactional-cls-hooked initialization

### ISSUE THREAD

**Issue by demostenes1509** [odavid/typeorm-transactional-cls-hooked#30]
Hi, @odavid !

This is not an issue, its just a warning to devs community. 

My app is spread between several modules, and in order to 'reuse' code, I did something like this:

```
import {
  initializeTransactionalContext,
  patchTypeORMRepositoryWithBaseRepository,
} from 'typeorm-transactional-cls-hooked';

export const initializeTransactions = () => {
  initializeTransactionalContext(); 
  patchTypeORMRepositoryWithBaseRepository(); 
};
```
And ...

```
import { initializeTransactions } from 'mylib';

async function bootstrap() {
  initializeTransactions();
...
...
```
Code above makes transactions dont work ! Transaction initialization must be in the SAME module that it will used. I spend 3 hours researching why library was not working ... haha !

Best, and my warm congrats for this esplendid library !

**Comment by Kerren-Entrostat** [comment]
Hi @demostenes1509 can you please elaborate on what you mean by "module" in this case?

Are you saying that it must be done in the `index.ts` of your application (assuming that's your entry point) or does that mean that you need to always have this import in the file when you're using the transaction decorator?

**Comment by demostenes1509** [comment]
> Hi @demostenes1509 can you please elaborate on what you mean by "module" in this case?
> 
> Are you saying that it must be done in the `index.ts` of your application (assuming that's your entry point) or does that mean that you need to always have this import in the file when you're using the transaction decorator?

What Im saying is: If you are adding another library
