### ISSUE TITLE
dist folder missing in package version 0.1.9

### ISSUE THREAD

**Issue by daffodil11** [odavid/typeorm-transactional-cls-hooked#33]
I've just upgraded to the latest version and I think the build step was missed when publishing, because he dist folder appears to be missing, which prevents the module from working.

**Comment by odavid** [comment]
Sorry for that. released 0.1.10

**Comment by odavid** [comment]
Please Let me know if you have any issues with 0.1.10

**Comment by daffodil11** [comment]
0.1.10 appears to work fine. Thank you!
