### ISSUE TITLE
Is propagation type SUPPORTS equivalent to no Transactional decorator? 

### ISSUE THREAD

**Issue by ydinari** [odavid/typeorm-transactional-cls-hooked#35]
Suppose I have function foo() decorated with @Transactional, calling function bar(). Do we get the same behavior if bar is decorated with @Transactional({ propagation: Propagation.SUPPORTS }), or not decorated at all? 
It seems that way by looking at the logs of start and commit transaction, but I'm not sure this is guaranteed.

**Comment by odavid** [comment]
Hi @ydinari ,

The answer is yes. 
`SUPPORTS` means that it supports the current transaction, but will run without transaction if there is no current transaction.

Hope it helps

**Comment by ydinari** [comment]
Thanks!
Then is there a use case where I need to use Transaction({propagation: Propagation.SUPPORTS})?

**Comment by odavid** [comment]
Basically I tried to emulate all spring options. I myself, not sure what
would be the use case for that.
