### ISSUE TITLE
Problem with repository injection

### ISSUE THREAD

**Issue by ydinari** [odavid/typeorm-transactional-cls-hooked#37]
Hi,
I'm trying out your package. It seems that for @Transactional to work all database access should be done using repositories (and not via EntityManager, correct me if I'm wrong).
I had a bunch of repositories doing operations on other database entities, using their local manager.
So I replaced those with repositories injection (each repository gets injected with any other repository it needs).
But this didn't work. Looking at the value of the injected repository in a debugger it is not of the repository type at all, but rather of type EntityManager. I guess I'm doing something wrong here but I don't know what.
Thanks

**Comment by odavid** [comment]
Hi,
Did you try patching repository with base repository?

https://github.com/odavid/typeorm-transactional-cls-hooked#patching-typeorm-repository-with-baserepository

**Comment by ydinari** [comment]
Yes, I'm calling it

**Comment by odavid** [comment]
Maybe this will help:
* https://github.com/odavid/typeorm-transactional-cls-hooked/issues/29
Or this one
* https://github.com/odavid/typeorm-transactional-cls-hooked/issues/30

Other than that, it will be hard for me to understand what is wrong

**Comment by ydinari** [comment]
Hi, It's not an issue with your package, it's an issue with nestjs/typeorm. It is not possible to inject repositories into other repositories :(

**Comment by odavid** [comment]
Thanks for letting me know. Can we close the issue?

**Comment by ydinari** [comment]
yes
