### ISSUE TITLE
Does TransactionRepository decorator work with Transactional?

### ISSUE THREAD

**Issue by ydinari** [odavid/typeorm-transactional-cls-hooked#38]
When working with typeorm Transaction decorator you can inject repositories as parameters to the decorated function using TransactionRepository decorator. Can you use that with the Transactional decorator?

**Comment by odavid** [comment]
Never tried that, so I cannot really tell. 
Seems a bit conflict to the `Transactional` concept, since  it must come with typeorm `@Transaction` decorator, which opens a transaction and closes it when the method finishes.
