### ISSUE TITLE
Specifying Isolation Levels

### ISSUE THREAD

**Issue by ashleyw** [odavid/typeorm-transactional-cls-hooked#4]
Hey! Would you be open to a PR to support isolation levels?

https://github.com/typeorm/typeorm/blob/master/docs/transactions.md#specifying-isolation-levels

Thanks!

**Comment by odavid** [comment]
Sure. This was one the things I wanted to have in day one, but the typeorm version I used, did not have it, only documented.
I wanted to get the same experience a spring developer has.
So if you are willing to contribute, I will for sure be open to it.
Best,
Ohad

**Comment by odavid** [comment]
@ashleyw - released [0.1.3](https://www.npmjs.com/package/typeorm-transactional-cls-hooked)
