### ISSUE TITLE
The usage TypeORM as active records is not supported ?

### ISSUE THREAD

**Issue by herbertpimentel** [odavid/typeorm-transactional-cls-hooked#40]
Just as in 
https://typeorm.io/#/active-record-data-mapper/what-is-the-active-record-pattern this way I really will have to change my typeorm interactions that are using active records to a repository pattern ?!

**Comment by odavid** [comment]
Hi @herbertpimentel, looking at the code of [typeorm BaseEntity class](https://github.com/typeorm/typeorm/blob/master/src/repository/BaseEntity.ts), I don't see any reason why active records should not work. Basically the "trick" in transactional is to keep the same EntityManager within the same context, while "patching" the repository object to always return the same EntityManager.

Having said that, I have not tested the active records pattern together with transactional

Cheers

**Comment by CodorMonkey** [comment]
Hi @herbertpimentel , @Transactional() works for me, and I am also using active-record. Please check carefully you are using @Transactional() , not @Transaction of typeorm.

register hook
`
async function bootstrap () {
  // before app create
  initializeTransactionalContext();
  patchTypeORMRepositoryWithBaseRepository();
  
  const app = await NestFactory.create(AppModule);
  ...other code
}
`

service may be like
`
...other imports
import { Transactional } from 'typeorm-transactional-cls-hooked';

@Injectable()
export class XxxService {

  @Transactional()
  async test () {
    
  }
}
`
I hope it helps you

**Comment by herbertpimentel** [comment]
@CodorMonkey It also worked to me but I end up not using this. Checkout this https://github.com/typeorm/typeorm/issues/5313#issuecomment-573626159

It still pending, but It is a side project so I will work on that when I have more time.
