### ISSUE TITLE
The @Transactional() decorator doesn't want to open a new transaction

### ISSUE THREAD

**Issue by ekifox** [odavid/typeorm-transactional-cls-hooked#54]
index.ts
```ts
export class Main {
     constructor(
        private readonly service: Service // Are injected from DI system
    ) {} 

     public load() {
          setTimeout(() => this.doJob(), 5000)
     }

     private async doJob() {
          await this.service.makeMeACake()
     }
}
```

service.ts
```ts
export class Service {
    constructor(readonly cakeRepository: CakeRepository) {}

    @Transactional()
    public async makeMeACake() {
        let cake = await this.cakeRepository.findOneOrFail(50, {
            lock: { mode: 'pessimistic_write' }
        })

        cake.status = ECakeStatus.CREATING
        await this.cakeRepository.update(cake.id, { status: cake.status })
    }
}
```

And here's what I caught when launching the application:
![image](https://user-images.githubusercontent.com/1989823/92758691-a6aa2080-f397-11ea-94dc-4b7c6f94fac6.png)

I don't use http server in this application. I have several functions, timer and service. Unfortunately for some reason the **@Transactional()** decorator doesn't want to open a new transaction in my case.
In the original, the code has more methods and is more complicated but the basic principle of calling functions is exactly the same as I had described. Where can I find the error? How to debug?

**Comment by odavid** [comment]
Hi @ekifox - do u initialize the cls-hooked before u start the application?

Like this? https://github.com/odavid/typeorm-transactional-cls-hooked#initialization

I have not tried that with "DI", but I believe the above is the main issue (Although, Not sure)

**Comment by ekifox** [comment]
![image](https://user-images.githubusercontent.com/1989823/92761241-289b4900-f39a-11ea-9093-a507a200598e.png)

I tried to start transaction by: await this.crashRepository.manager.connection.createQueryRunner().startTransaction()
and it does not help.

Yes, I'm do the initialization before start the application:
![image](https://user-images.githubusercontent.com/1989823/92761451-60a28c00-f39a-11ea-88d7-23c28150a34c.png)

Very strange, but other methods from this service are working successfully. The queries are ran in one transaction.
But not with **finishRound**.

**Comment by ekifox** [comment]
I've found a strange solution for the problem. If setTimeout is set with minus value then the finishRound is ran without transaction. If i will wait for 5 sec. or more the transaction is propagated to finishRound and all the works nice.
The only one what I think now is the other function in this context is caught the connection and ran a transaction.

**Comment by ekifox** [comment]
After a little bit of digging, I've found that I have a separate function that runs in same context at the same time. And that causes the transaction and entity manager capturing from one function to another one.

**Comment by ekifox** [comment]
So, how to create a new context for other function that run in the background?

**Comment by odavid** [comment]
```typescript
public load() {
   setTimeout(() => this.doJob(), 5000)
}
```

Seems to me the problem is related to the load() function that is not async and it calls to setTimeout that does not await and does not return a promise. I believe this creates a mess in how cls-hooked is expecting things to work. I am really not an expert here ): - I think you should try to see how to implement the background process in a different manner. Maybe you need to return a promise and make the load() transactional and async...

I am really sorry I cannot help more than that, and also if I am saying "stupid" things 😉

**Comment by ekifox** [comment]
@odavid thank you for your answer. I rewrite my code and last question is how to create a new CLS context before functions call?
I cant understand it by cls-hooked docs :(
I assume that my question is not refers to yours package. Question is globally to cls-hooked, but I think you can help me to solve the problem :)

**Comment by ekifox** [comment]
I want to run one '@Transactional()' function with different arguments concurrently. Every call of this function needs to be in other own transaction (and DB connection of course).

**Comment by ekifox** [comment]
```ts
public async run() {
    for (let i = 0; i < 50; i++) {
        createNewContextToRunInDifferentTransaction()
        this.makeMeACake(i)
    }
}

@Transactional()
public async makeMeACake(id: number) {
    let cake = await this.cakeRepository.findOneOrFail(id, {
        lock: { mode: 'pessimistic_write' }
     })

     cake.status = ECakeStatus.CREATING
     await this.cakeRepository.update(cake.id, { status: cake.status })
}
```
I need something like this :)

**Comment by ekifox** [comment]
> I believe this creates a mess in how cls-hooked is expecting things to work.

I make some test with await and without. Yes, cls-hooked really loses context then child called in parent without await :(
