### ISSUE TITLE
suggest to turn this lib into a patch

### ISSUE THREAD

**Issue by Diluka** [odavid/typeorm-transactional-cls-hooked#8]
```ts
for (const p of Object.getOwnPropertyNames(BaseRepository.prototype)) {
  Object.defineProperty(Repository.prototype, p, Object.getOwnPropertyDescriptor(BaseRepository.prototype, p));
}
```

If modified `Repository`, it can also support `ActivieRecord`!

**Comment by odavid** [comment]
Thanks!
I would like to keep the package without meta programming...  
Anyone can do it at application start, if I get it right.
Regards,
Ohad

**Comment by Diluka** [comment]
@odavid Understood
If someone just want to using `@Transactional()` to make things happen without change existing code. This patch maybe helps.
https://gist.github.com/Diluka/87efbd9169cae96a012a43d1e5695667
